server:
  port: 9033
spring:
  application:
    name: basicsystem
  datasource:
    url: jdbc:mysql://localhost:3306/system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: dubbo
    port: 50051
  application:
    qos-enable: true
    name: BasicSystemApi
    qos-port: 22222
    qos-accept-foreign-ip: false
    logger: slf4j


logging:
  level:
    root: debug